# Generated by Django 3.2.8 on 2021-10-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='critic',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
