# Generated by Django 3.2.8 on 2021-12-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20211102_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='normalized_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
