# Generated by Django 3.2.8 on 2021-12-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_review_normalized_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='standard_deviation',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
    ]
