# Generated by Django 3.2.8 on 2021-12-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20211203_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='standard_deviation',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
    ]
