# Generated by Django 3.2.9 on 2021-12-07 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20211204_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='personalized_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
